#!/usr/bin/env python3
"""Draw each lesson's pins - on the board and in the chip - into its Slide.md.

Students otherwise meet "PA6" and "PB8" as names and have to imagine where
they are.  This draws two pictures per lesson, derived rather than drawn:

  BOARD VIEW  the Nucleo-C031C6's headers to scale, as Wokwi lays them out,
              with the exact header pins the lesson's diagram.json wires to
              highlighted and labelled.  Positions come from Wokwi's board
              definition; which pins, from the lesson's own diagram.json - so
              the picture cannot disagree with the circuit students paste.

  CHIP VIEW   ports A and B as sixteen bit-cells each, pin 15 on the left and
              pin 0 on the right (the order registers are drawn in), with the
              lesson's pins marked by what they are configured as.  That part
              is course knowledge, in the LESSONS table below.

Usage (from projects2026_arm/):
    python _build/pinmap.py              # regenerate every lesson's pictures
    python _build/pinmap.py --refresh    # re-derive the layout facts from Wokwi
    python _build/pinmap.py --refresh board.json   # ... from a local copy

The layout facts are _targets/c031c6-layout.json: pin name -> (x, y) in mm.
Like c031c6-pins.json, they are facts derived from Wokwi's board file, which
declares no licence, so the file itself is not vendored.

Where the pictures go: a Slide.md opts in by containing a ```svg block whose
first line is the marker comment below.  Only those blocks are rewritten; a
comment inside SVG is invisible when rendered.
"""
import datetime
import json
import os
import re
import sys

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LAYOUT = os.path.join(BASE, "_targets", "c031c6-layout.json")
PINS = os.path.join(BASE, "_targets", "c031c6-pins.json")
SOURCE = ("https://raw.githubusercontent.com/wokwi/wokwi-boards/main/"
          "boards/st-nucleo-c031c6/board.json")

MARK_BOARD = "<!-- pinmap:board - generated by _build/pinmap.py; edit the lesson's diagram.json or pinmap.py, not this -->"
MARK_CHIP = "<!-- pinmap:chip - generated by _build/pinmap.py; edit pinmap.py's LESSONS table, not this -->"

# What each lesson configures each pin as.  (mode, what it is)
#   mode: "in", "out", "af<N>", "an" - drives the chip view's cell text.
LESSONS = {
    "04_Startup_And_LinkerScript": {
        "PA5": ("out", "LD4, the on-board LED"),
        "PA2": ("af1", "USART2 TX - serial monitor"),
        "PA3": ("af1", "USART2 RX - serial monitor"),
        **{f"PB{i}": ("out", f"LED bar bit {i}") for i in range(8)},
    },
    "05_GPIO_And_Interrupts": {
        "PA0": ("in", "button A - polled, pull-up"),
        "PA1": ("in", "button B - EXTI line 1, pull-up"),
        "PA5": ("out", "LD4 heartbeat"),
        "PA2": ("af1", "USART2 TX - serial monitor"),
        "PA3": ("af1", "USART2 RX - serial monitor"),
        **{f"PB{i}": ("out", f"LED bar bit {i}") for i in range(8)},
    },
    "06_Time_And_Timers": {
        "PA5": ("out", "LD4 heartbeat"),
        "PA6": ("af1", "TIM3_CH1 PWM - servo"),
        "PA7": ("af4", "TIM14_CH1 capture - echo"),
        "PA8": ("out", "HC-SR04 trigger"),
        "PA2": ("af1", "USART2 TX - serial monitor"),
        "PA3": ("af1", "USART2 RX - serial monitor"),
        **{f"PB{i}": ("out", f"proximity bar bit {i}") for i in range(8)},
    },
    "07_RTOS": {
        "PA0": ("in", "button A - bar speed, pull-up"),
        "PA1": ("in", "button B - hog on/off, pull-up"),
        "PA2": ("af1", "USART2 TX - serial monitor"),
        "PA3": ("af1", "USART2 RX - serial monitor"),
        **{f"PB{i}": ("out", f"LED bar bit {i}") for i in range(8)},
    },
    "08_UART_And_Python_Host": {
        "PA0": ("in", "button A - counted, pull-up"),
        "PA1": ("in", "button B - counted, pull-up"),
        "PA2": ("af1", "USART2 TX - interrupt driven"),
        "PA3": ("af1", "USART2 RX - interrupt driven"),
        **{f"PB{i}": ("out", f"LED bar bit {i}") for i in range(8)},
    },
    "09_Sensors_And_Buses": {
        "PA4": ("an", "ADC_IN4 - potentiometer"),
        "PB8": ("af6", "I2C1 SCL - MPU6050"),
        "PB9": ("af6", "I2C1 SDA - MPU6050"),
        "PA5": ("af0", "SPI1 SCK - MAX7219 (and LD4)"),
        "PA7": ("af0", "SPI1 MOSI - MAX7219 DIN"),
        "PB0": ("out", "MAX7219 chip select"),
        "PA2": ("af1", "USART2 TX - serial monitor"),
        "PA3": ("af1", "USART2 RX - serial monitor"),
    },
}

# On-board things a lesson uses that no diagram.json wire names.
ONBOARD = {"PA5": "LD4 (on the board)"}

S = 6.0          # px per mm
BX, BY = 300, 46  # where the board's top-left corner goes
SIDE = 300       # label space each side


# ---------------------------------------------------------------------------
# --refresh: Wokwi's board file -> the layout facts
# ---------------------------------------------------------------------------
def refresh(path):
    if path:
        raw = open(path, encoding="utf-8").read()
    else:
        import urllib.request
        raw = urllib.request.urlopen(SOURCE, timeout=30).read().decode("utf-8")
    raw = re.sub(r"//[^\n]*", "", raw)                 # JSON5-ish: // comments
    raw = re.sub(r",(\s*[}\]])", r"\1", raw)            # ... and trailing commas
    board = json.loads(raw)
    facts = {
        "board": board["name"],
        "source": SOURCE,
        "derived": datetime.date.today().isoformat(),
        "note": "Header pin positions in mm, derived from Wokwi's board definition. "
                "Regenerate with python _build/pinmap.py --refresh",
        "width_mm": board["width"],
        "height_mm": board["height"],
        "pins": {k: [round(v["x"], 2), round(v["y"], 2)] for k, v in board["pins"].items()},
    }
    with open(LAYOUT, "w", encoding="utf-8", newline="\n") as f:
        json.dump(facts, f, indent=1, sort_keys=False)
        f.write("\n")
    print(f"wrote {os.path.relpath(LAYOUT, BASE)}: {len(facts['pins'])} pins")


# ---------------------------------------------------------------------------
# Pictures
# ---------------------------------------------------------------------------
def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def spread(items, top, gap):
    """items: [(pin_y, ...)] sorted by y.  Returns [(label_y, pin_y, ...)] with
    labels pushed down so no two are closer than `gap`."""
    out, last = [], top - gap
    for it in items:
        y = max(it[0], last + gap)
        out.append((y,) + tuple(it))
        last = y
    return out


def wired_pins(lesson, layout, targets):
    """Header pins the lesson's diagram.json wires to: name -> list of other ends."""
    d = json.load(open(os.path.join(BASE, lesson, "diagram.json"), encoding="utf-8"))
    parts = {p["id"]: p for p in d["parts"]}
    ends = {}
    for c in d["connections"]:
        a, b = c[0], c[1]
        for mine, other in ((a, b), (b, a)):
            if mine.startswith("nucleo:"):
                name = mine.split(":", 1)[1]
                pid = other.split(":", 1)[0]
                if pid == "$serialMonitor":
                    what = "serial monitor"
                else:
                    p = parts.get(pid, {})
                    what = p.get("attrs", {}).get("label") or pid
                ends.setdefault(name, []).append(what)
    return ends


def board_svg(lesson, layout, targets):
    roles = LESSONS[lesson]
    ends = wired_pins(lesson, layout, targets)
    W = layout["width_mm"] * S
    H = layout["height_mm"] * S
    vw, vh = BX + W + SIDE, BY + H + 62
    o = [MARK_BOARD,
         f'<svg viewBox="0 0 {int(vw)} {int(vh)}" role="img" '
         f'aria-label="Nucleo-C031C6 headers to scale, with this lesson\'s pins highlighted">',
         f'  <text x="{vw / 2:.0f}" y="18" text-anchor="middle" class="lbl">'
         f'Nucleo-C031C6 headers, to scale, as Wokwi lays them out - this lesson\'s wires highlighted</text>',
         f'  <rect class="box" x="{BX}" y="{BY}" width="{W:.0f}" height="{H:.0f}" rx="10"/>',
         f'  <text x="{BX + W / 2:.0f}" y="{BY + 34:.0f}" text-anchor="middle" class="lbl">Nucleo-C031C6 (MB1717)</text>',
         f'  <text x="{BX + W / 2:.0f}" y="{BY + 52:.0f}" text-anchor="middle" class="lbl">headers only - components not drawn</text>']

    # every header pin, faint
    for name, (x, y) in layout["pins"].items():
        o.append(f'  <circle cx="{BX + x * S:.1f}" cy="{BY + y * S:.1f}" r="3.2" '
                 f'fill="none" stroke="currentColor" stroke-opacity="0.35"/>')

    # column captions
    cols = [(4.07, "ST morpho", 18), (10.3, "Arduino", 34), (59.3, "Arduino", 34), (65.7, "ST morpho", 18)]
    for x, t, dy in cols:
        o.append(f'  <text x="{BX + x * S:.0f}" y="{BY + H + dy:.0f}" text-anchor="middle" class="lbl">{t}</text>')

    # the lesson's pins: every wired header position, plus on-board ones
    marks = {}          # header name -> label
    for name, others in ends.items():
        tgt = targets.get(name, name)
        if not tgt.startswith("P"):          # power / ground: small, unlabelled list
            marks[name] = (tgt.replace("power(3.3)", "3V3").replace("power(5)", "5V"), True)
            continue
        role = roles.get(tgt, ("", ", ".join(sorted(set(others)))))[1]
        alias = "" if name == tgt else f" ({name})"
        marks[name] = (f"{tgt}{alias}  {role}", False)
    for tgt, text in ONBOARD.items():
        if tgt in roles and not any(targets.get(n) == tgt for n in ends):
            marks[tgt] = (f"{tgt}  {roles[tgt][1]} (on-board)", False)

    left, right, power = [], [], []
    for name, (text, is_power) in marks.items():
        x, y = layout["pins"][name]
        px, py = BX + x * S, BY + y * S
        if is_power:
            power.append((px, py, text))
            continue
        (left if x < layout["width_mm"] / 2 else right).append((py, px, text))

    for px, py, text in power:
        o.append(f'  <circle cx="{px:.1f}" cy="{py:.1f}" r="4" fill="currentColor" fill-opacity="0.45"/>')
    for side, items in (("L", sorted(left)), ("R", sorted(right))):
        for ly, py, px, text in spread(items, BY + 8, 15):
            if side == "L":
                tx, anchor, ex = BX - 14, "end", BX - 8
            else:
                tx, anchor, ex = BX + W + 14, "start", BX + W + 8
            o.append(f'  <path class="dash" d="M{px:.1f} {py:.1f} L{ex:.1f} {ly:.1f}"/>')
            o.append(f'  <circle class="hifill" cx="{px:.1f}" cy="{py:.1f}" r="5"/>')
            o.append(f'  <circle class="hi" cx="{px:.1f}" cy="{py:.1f}" r="5" fill="none"/>')
            o.append(f'  <text x="{tx:.1f}" y="{ly + 4:.1f}" text-anchor="{anchor}" class="mono" '
                     f'font-size="13">{esc(text)}</text>')
    if power:
        names = sorted(set(t for _, _, t in power))
        o.append(f'  <text x="{vw / 2:.0f}" y="{vh - 6:.0f}" text-anchor="middle" class="lbl">'
                 f'grey dots: power and ground wires ({", ".join(names)})</text>')
    o.append("</svg>")
    return o


def is_bar(role):
    return role.startswith(("LED bar", "proximity bar"))


def chip_lines(roles, port):
    """Caption lines under a port row: one per pin, the LED bar folded into one."""
    pins = sorted((n for n in roles if n[1] == port), key=lambda n: -int(n[2:]))
    lines, bar_done = [], False
    for n in pins:
        mode, what = roles[n]
        if is_bar(what):
            if not bar_done:
                bars = [p for p in pins if is_bar(roles[p][1])]
                lines.append(f"{bars[0]}..{bars[-1]}  {mode:4} {what.rsplit(' bit', 1)[0]}, one bit per LED")
                bar_done = True
            continue
        lines.append(f"{n:5} {mode:4} {what}")
    return lines


def chip_svg(lesson):
    roles = LESSONS[lesson]
    ports = sorted({p[1] for p in roles})                  # 'A', 'B'
    cw, ch, x0 = 32, 34, 88
    vw = x0 + 16 * cw + 20
    rows = [(port, chip_lines(roles, port)) for port in ports]
    heights = [ch + 16 + 15 * len(lines) + 18 for _, lines in rows]
    vh = 40 + sum(heights) + 24
    o = [MARK_CHIP,
         f'<svg viewBox="0 0 {vw} {vh}" role="img" aria-label="Ports as register bits, with this lesson\'s pins marked">',
         f'  <text x="{vw / 2:.0f}" y="18" text-anchor="middle" class="lbl">'
         f'Inside the chip: each port is 16 pins, drawn in register order - pin 15 left, pin 0 right</text>']
    y = 40
    for (port, lines), hgt in zip(rows, heights):
        o.append(f'  <text x="{x0 - 12}" y="{y + ch / 2 + 5:.0f}" text-anchor="end" class="mono">GPIO{port}</text>')
        for i in range(16):
            pin = 15 - i
            x = x0 + i * cw
            name = f"P{port}{pin}"
            used = name in roles
            debug = name in ("PA13", "PA14")
            cls = "hifill" if used else "reg"
            o.append(f'  <rect class="{cls}" x="{x}" y="{y}" width="{cw - 3}" height="{ch}" rx="3"/>')
            o.append(f'  <text x="{x + (cw - 3) / 2:.1f}" y="{y + 14}" text-anchor="middle" class="mono lbl">{pin}</text>')
            if used:
                mode = roles[name][0].upper().replace("AF", "AF")
                txt = {"IN": "in", "OUT": "out", "AN": "an"}.get(mode, mode.lower())
                o.append(f'  <text x="{x + (cw - 3) / 2:.1f}" y="{y + 28}" text-anchor="middle" class="mono">{txt}</text>')
            elif debug:
                o.append(f'  <text x="{x + (cw - 3) / 2:.1f}" y="{y + 28}" text-anchor="middle" class="lbl">SWD</text>')
        for k, line in enumerate(lines):
            o.append(f'  <text x="{x0}" y="{y + ch + 20 + 15 * k}" class="mono lbl" '
                     f'xml:space="preserve">{esc(line)}</text>')
        y += hgt
    o.append(f'  <text x="{vw / 2:.0f}" y="{vh - 8}" text-anchor="middle" class="lbl">'
             f'in = MODER 00 · out = 01 · afN = 10 with AFR = N · an = 11 - lesson 05, slides 4-5</text>')
    o.append("</svg>")
    return o


def replace_block(text, marker, new_lines):
    lines = text.split("\n")
    out, i, hits = [], 0, 0
    while i < len(lines):
        if lines[i].strip() == "```svg" and i + 1 < len(lines) and lines[i + 1].strip() == marker:
            out.append("```svg")
            out.extend(new_lines)
            i += 1
            while i < len(lines) and lines[i].strip() != "```":
                i += 1
            out.append("```")
            i += 1
            hits += 1
            continue
        out.append(lines[i])
        i += 1
    return "\n".join(out), hits


def generate():
    layout = json.load(open(LAYOUT, encoding="utf-8"))
    targets = json.load(open(PINS, encoding="utf-8"))["pins"]
    for lesson in LESSONS:
        slide = os.path.join(BASE, lesson, "Slide.md")
        text = open(slide, encoding="utf-8").read()
        text, hb = replace_block(text, MARK_BOARD, board_svg(lesson, layout, targets))
        text, hc = replace_block(text, MARK_CHIP, chip_svg(lesson))
        with open(slide, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print(f"  {lesson:30} board view {'updated' if hb else 'NO MARKER'}, "
              f"chip view {'updated' if hc else 'NO MARKER'}")


if __name__ == "__main__":
    if "--refresh" in sys.argv:
        rest = [a for a in sys.argv[1:] if a != "--refresh"]
        refresh(rest[0] if rest else None)
    else:
        generate()
