#!/usr/bin/env python3
"""
embed_shots.py - put the host test's screenshots into Slide.md.   lesson 12

host/test_games.c writes host/out/<name>.svg: the real framebuffer after the
real game code ran.  Slide.md shows them in ```svg blocks whose first line is
a marker comment:

    <!-- shot:snake - generated by host/embed_shots.py from host/out/*.svg -->

This script rewrites every such block from the current files, so the deck
cannot drift from what the code draws.  "quad" is the menu and the three games
in a 2 x 2 grid.  A block written as the single line  @@SVG:name@@  is turned
into a marked block the first time.

    bash host/run.sh && python host/embed_shots.py

Standard library only.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "out")
SLIDE = os.path.join(os.path.dirname(HERE), "Slide.md")
MARK = "<!-- shot:%s - generated by host/embed_shots.py from host/out/*.svg -->"


def path_of(name):
    with open(os.path.join(OUT, name + ".svg"), encoding="utf-8") as f:
        text = f.read()
    m = re.search(r'<path fill="currentColor" d="([^"]*)"', text)
    if not m:
        raise SystemExit("no path in %s.svg - run host/run.sh first" % name)
    return " ".join(m.group(1).split())


def screen(name, dx=0, dy=0, label=None):
    s = '  <g transform="translate(%d %d)">\n' % (dx, dy)
    s += ('    <rect x="-1.5" y="-1.5" width="131" height="67" rx="2" fill="none" '
          'stroke="currentColor" stroke-opacity="0.4"/>\n')
    s += '    <path fill="currentColor" d="%s"/>\n' % path_of(name)
    if label:
        s += '    <text x="64" y="76" text-anchor="middle" class="lbl" font-size="6">%s</text>\n' % label
    return s + "  </g>\n"


def block(name):
    if name == "quad":
        body = ('<svg viewBox="-4 -4 272 166" role="img" aria-label="The menu and the three '
                'games, rendered on the host from the real game code">\n')
        body += screen("menu", 0, 0, "menu")
        body += screen("snake", 136, 0, "SNAKE")
        body += screen("breakout", 0, 82, "BREAKOUT")
        body += screen("flap", 136, 82, "FLAP")
    else:
        body = ('<svg viewBox="-4 -4 136 72" role="img" aria-label="%s, rendered on the '
                'host from the real game code">\n' % name)
        body += screen(name)
    body += "</svg>"
    return "```svg\n" + (MARK % name) + "\n" + body + "\n```"


def main():
    with open(SLIDE, encoding="utf-8") as f:
        text = f.read()
    n = 0

    def first(m):
        nonlocal n
        n += 1
        return block(m.group(1))
    text = re.sub(r"^@@SVG:(\w+)@@$", first, text, flags=re.M)

    def again(m):
        nonlocal n
        n += 1
        return block(m.group(1))
    text = re.sub(r"```svg\n<!-- shot:(\w+) - generated[^\n]*-->\n.*?\n```", again, text, flags=re.S)

    with open(SLIDE, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("embedded %d screenshot block(s) into %s" % (n, os.path.relpath(SLIDE)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
