/*
 * fix.c - the table-driven part of fix.h   (SOC3050 lesson 10)
 *
 * Pure C, compiled into the firmware and into host/test_fix.c alike.
 */
#include "fix.h"

/* sin(90 deg * i / 64) in Q15, i = 0..64, rounded; the last entry is
 * clamped to 32767 because +1.0 does not exist in Q15.  Generated by:
 *   [min(32767, round(32768*sin(pi/2*i/64))) for i in range(65)]
 * 65 x 2 bytes = 130 bytes of flash, in .rodata - never copied to RAM. */
static const q15_t quarter[65] = {
        0,   804,  1608,  2411,  3212,  4011,  4808,  5602,
     6393,  7180,  7962,  8740,  9512, 10279, 11039, 11793,
    12540, 13279, 14010, 14733, 15447, 16151, 16846, 17531,
    18205, 18868, 19520, 20160, 20788, 21403, 22006, 22595,
    23170, 23732, 24279, 24812, 25330, 25833, 26320, 26791,
    27246, 27684, 28106, 28511, 28899, 29269, 29622, 29957,
    30274, 30572, 30853, 31114, 31357, 31581, 31786, 31972,
    32138, 32286, 32413, 32522, 32610, 32679, 32729, 32758,
    32767,
};

/* A binary angle: 0..65535 is one full turn.  Bits 15:14 pick the quadrant,
 * bits 13:8 the table entry, bits 7:0 how far towards the next entry. */
q15_t q15_sin(uint16_t angle)
{
    uint32_t quadrant = angle >> 14;
    uint32_t a        = angle & 0x3FFFu;            /* 0..16383 inside it   */
    if (quadrant & 1u) { a = 16384u - a; }          /* mirror: 2nd and 4th  */

    uint32_t i    = a >> 8;                          /* 0..64                */
    int32_t  frac = (int32_t)(a & 0xFFu);            /* 0..255               */
    int32_t  y0   = quarter[i];
    int32_t  y1   = (i < 64u) ? quarter[i + 1u] : y0;
    int32_t  y    = y0 + (((y1 - y0) * frac + 128) >> 8);   /* interpolate, rounded */

    return (q15_t)((quadrant & 2u) ? -y : y);       /* 3rd and 4th: negative */
}
